config/routes.rb
Rails.application.routes.draw do
  get 'acount/mypage' => 'acount#mypage'
  get 'score/main' =>'score#main'
  get 'tweets/:id/consent' => "tweets#consent", as: "tweet_consent"
  get 'partscores/:id/consent' => "partscores#consent", as: "partscore_consent"
  get 'pbasses/:id/consent' => "pbasses#consent", as: "pbass_consent"
  get 'pdrums/:id/consent' => "pdrums#consent", as: "pdrum_consent"
  get 'pkeyboards/:id/consent' => "pkeyboards#consent", as: "pkeyboard_consent"
  get 'dictations/:id/consent' => "dictations#consent", as: "dictation_consent"
  get 'dbasses/:id/consent' => "dbasses#consent", as: "dbass_consent"
  get 'ddrums/:id/consent' => "ddrums#consent", as: "ddrum_consent"
  get 'dkeyboards/:id/consent' => "dkeyboards#consent", as: "dkeyboard_consent"
  get 'd_choruses/:id/consent' => "d_choruses#consent", as: "dchorus_consent"
  get 'music/main' => 'music#main'

  get 'tweets/new' => 'tweets#new'
  post 'tweets/create' => 'tweets#create'
  get 'tweets' => 'tweets#index'
  post 'tweets' => "tweets#index"

  get 'partscores/new' =>'partscores#new'
  post  'partscores/create' => 'partscores#create'
  get 'partscores' => 'partscores#index'
  post 'partscores' => "partscores#index"

  get 'pbasses/new' =>'pbasses#new'
  post  'pbasses/create' => 'pbasses#create'
  get 'pbasses' => 'pbasses#index'
  post 'pbasses' => "pbasses#index"

  get 'pdrums/new' =>'pdrums#new'
  post  'pdrums/create' => 'pdrums#create'
  get 'pdrums' => 'pdrums#index'
  post 'pdrums' => "pdrums#index"

  get 'pkeyboards/new' => 'pkeyboards#new'
  post 'pkeyboards/create' => 'pkeyboards#create'
  get 'pkeyboards' => 'pkeyboards#index'
  post 'pkeyboards' => "pkeyboards#index"

  get 'dictations/new' =>'dictations#new'
  post  'dictations/create' => 'dictations#create'
  get 'dictations' => 'dictations#index'
  post 'dictations' => "dictations#index"

  get 'dbasses/new' =>'dbasses#new'
  post  'dbasses/create' => 'dbasses#create'
  get 'dbasses' => 'dbasses#index'
  post 'dbasses' => "dbasses#index"

  get 'ddrums/new' =>'ddrums#new'
  post  'ddrums/create' => 'ddrums#create'
  get 'ddrums' => 'ddrums#index'
  post 'ddrums' => "ddrums#index"

  get 'dkeyboards/new' => 'dkeyboards#new'
  post 'dkeyboards/create' => 'dkeyboards#create'
  get 'dkeyboards' => 'dkeyboards#index'
  post 'dkeyboards' => "dkeyboards#index"

  get 'd_choruses/new' => 'd_choruses#new'
  post 'd_choruses/create' => 'd_choruses#create'
  get 'd_choruses' => 'd_choruses#index'
  post 'd_choruses' => "d_choruses#index"

  post 'tweets' => "tweets#index"
  get 'tweets/complete' => 'tweets#complete'
  devise_for :users
  resources :users, only: [:index, :detail, :edit, :destroy, :update]
  resources :tweets, only: [:edit, :show, :update, :destroy]
  resources :partscores, only: [:edit, :show, :update, :destroy]
  resources :pbasses, only: [:edit, :show, :update, :destroy]
  resources :pdrums, only: [:edit, :show, :update, :destroy]
  resources :pkeyboards, only: [:edit, :show, :update, :destroy]
  resources :dictations, only: [:edit, :show, :update, :destroy]
  resources :dbasses, only: [:edit, :show, :update, :destroy]
  resources :ddrums, only: [:edit, :show, :update, :destroy]
  resources :dkeyboards, only: [:edit, :show, :update, :destroy]
  resources :d_choruses, only: [:edit, :show, :update, :destroy]

  delete 'users/sign_out' =>'users#sign_out'
  root 'music#main'

  post 'requests/:id/create' => 'requests#create', as: 'new_request'
  put 'requests/update' => 'requests#update'
  post 'pgrequests/:id/create' => 'pgrequests#create', as: 'new_pgrequest'
  put 'pgrequests/update' => 'pgrequests#update'
  post 'pbrequests/:id/create' => 'pbrequests#create', as: 'new_pbrequest'
  put 'pbrequests/update' => 'pbrequests#update'
  post 'pdrequests/:id/create' => 'pdrequests#create', as: 'new_pdrequest'
  put 'pdrequests/update' => 'pdrequests#update'
  post 'pkrequests/:id/create' => 'pkrequests#create', as: 'new_pkrequest'
  put 'pkrequests/update' => 'pkrequests#update'
  post 'dgrequests/:id/create' => 'dgrequests#create', as: 'new_dgrequest'
  put 'dgrequests/update' => 'dgrequests#update'
  post 'dbrequests/:id/create' => 'dbrequests#create', as: 'new_dbrequest'
  put 'dbrequests/update' => 'dbrequests#update'
  post 'ddrequests/:id/create' => 'ddrequests#create', as: 'new_ddrequest'
  put 'ddrequests/update' => 'ddrequests#update'
  post 'dkrequests/:id/create' => 'dkrequests#create', as: 'new_dkrequest'
  put 'dkrequests/update' => 'dkrequests#update'
  post 'dcrequests/:id/create' => 'dcrequests#create', as: 'new_dcrequest'
  put 'dcrequests/update' => 'dcrequests#update'

  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end



end

app/controllers/dbasses_controller.rb
class DbassesController < ApplicationController
  def consent
    @dbass = Dbass.find(params[:id])
  end
  def index
    @dbasses = Dbass.all
    if params[:search] == nil
        @dbasses = Dbass.all
      elsif params[:search] == ""
        @dbasses = Dbass.all
      else
        @dbasses = Dbass.where("artist LIKE ? ",'%' + params[:search] + '%').or(Dbass.where("songs LIKE ? ", "%" + params[:search] + "%"))
      end
  end
  def new
    @dbass = Dbass.new
  end
  def show
    @dbass = Dbass.find(params[:id])
  end

  def create
    @dbass = Dbass.new(dbass_params)
    @dbass.user_id=current_user.id
  #新しいTweetの保存に成功した場合
    if @dbass.save
      #index.html.erbにページが移る
      redirect_to action: "index"
    #新しいTweetの保存に失敗した場合
    else
      #もう一回投稿画面へ
      redirect_to action: "new"
    end
  end
  def edit
    @dbass = Dbass.find(params[:id])
  end
  def update
    @dbass = Dbass.find(params[:id])
    @dbass.update(params.require(:dbass).permit(:artist,:songs,:discription,:request))
    redirect_to action: "index"
  end
  def destroy
    @dbass = Dbass.find(params[:id])
    @dbass.destroy
    redirect_to action: "index"
  end
  private
 #セキュリティのため、許可した:bodyというデータだけ取ってくるようにする
  def dbass_params
    params.require(:dbass).permit(:artist,:songs,:discription,:request)
  end
end

app/helpers/dbasses_helper.rb
module DbassesHelper
end

app/views/dbasses/consent.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheets" href="/assets//consent.scss" />
    <script language="javascript" type="text/javascript">

    </script>
    <title>consent</title>
  </head>
  <body class="consent">
    <div class="prohabited-matter">
      <p>
        ・借りる人は、紛失・破損等起きた場合は責任を持って弁償するなど、貸出者にもとの状態で返す義務をもつ。
      </p>
      <p>
        ・貸出者から借りたものを第三者に貸し出すこと（又貸し行為）は禁止である。
      </p>
      <p>
        ・貸出者が指定した期限以内に返す。返さない場合もまた、借りた人は弁償する。
      </p>
      <p>
        ・著作権の問題を考慮し、いかなるSNSなどの媒体でも公にスコアを発信しない。
      </p>
      <p>
        ・悪質な行為・いたずらをした場合はアカウントを停止する。
      </p>
    </div>
      <p class="checkbox">
        <input type="checkbox" id="check" autocomplete="off">
        <label for="check" class="check">上記に同意する</label>
      </p>
      <div class="btn">
        <%= button_to 'リクエストを送る', new_dbrequest_path(@dbass),:id => "submit", :class =>"btn" %>
      </div>
      <script type="text/javascript">
        $(function () {
          $('#submit').attr('disabled', 'disabled');
          $('#check').click(function () {
            if ($(this).prop('checked') == false) {
              $('#submit').attr('disabled', 'disabled');
            } else {
              $('#submit').removeAttr('disabled');
            }
          });
        });
      </script>


  </body>
</html>

app/views/dbasses/edit.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheets" href="/css/bootstrap.scss" />
    <link rel="stylesheets" href="/assets//dictations.scss" />
    <title>dictation</title>
  </head>
  <body class="dictation">
    <h1>スコア登録</h1>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dictation
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="../tweets/new">Band Score</a>
        <a class="dropdown-item" href="../partscores/new">Part Score</a>
        <a class="dropdown-item" href="/dictations/new">Dictation</a>
      </div>
    </div>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Bass
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="../dictations/new">Guitar</a>
        <a class="dropdown-item" href="/dbasses/new">Bass</a>
        <a class="dropdown-item" href="../ddrums/new">Drums</a>
        <a class="dropdown-item" href="../dkeyboards/new">Keyboard</a>
        <a class="dropdown-item" href="../d_choruses/new">Chorus</a>
      </div>
    </div>
    <%= form_for @dbass do |f| %>
    <div class="field">
      <p>歌手名</p>
      <small>(正式名で書く)</small>
      <br>
      <%= f.text_field :artist ,:class => "artist" %>
    </div>
    <div class="field">
      <p>曲名</p>
      <small>(正式名で書く)</small>
      <br>
      <%= f.text_field :songs ,:class => "songs" %>
    </div>
    <div class="field">
      <p>貸出者からの説明</p>
      <%= f.text_field :discription ,:class => "discription" %>
    </div>
    <div class="field">
      <p>貸出者からのお願い</p>
       <%= f.text_field :request ,:class => "request" %>
    </div>
    <div class="action">
       <%= f.submit %>
    </div>
    <% end %>
    <%= link_to "My Page", { :controller => "acount", :action => "mypage"}, :method => :get ,:class => "back_btn" %>
  </body>
</html>

app/views/dbasses/index.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheets" href="pblist.scss" />
    <title>partscore</title>
  </head>
  <body class="pblist">
    <h1 class="Partscore">Dictation</h1>
    <h5>アーティスト名or曲名で検索</h5>
    <%= form_tag(controller:"dbasses",action:"index") do %>
      <%= text_field_tag :search %>
      <%= submit_tag 'search',:artist => nil ,:songs => nil%>
    <% end %>
    <ul class="nav">
      <li class="pguitar"><%= link_to "Guitar", { :controller => "dictations", :action => "index"}, :method => :get ,:class => "nav" %></li>
      <li class="pbass"><%= link_to "Bass", { :controller => "dbasses", :action => "index"}, :method => :get ,:class => "nav" %></li>
      <li class="pdrums"><%= link_to "Drums", { :controller => "ddrums", :action => "index"}, :method => :get ,:class => "nav" %></li>
      <li class="pkeyboads"><%= link_to "Keyboards", { :controller => "dkeyboards", :action => "index"}, :method => :get ,:class => "nav" %></li>
      <li class="dchorus"><%= link_to "Chorus", { :controller => "d_choruses", :action => "index"}, :method => :get ,:class => "nav" %></li>
    </ul>

    <div class="position">
        <table class="partscore">
          <tr>
            <th>
              artist
            </th>
            <th>
              song
            </th>
          </tr>
          <% @dbasses.each do |t|  %>
          <tr>
            <td>
              <a href="/dbasses/<%= t.id %>" class="show"><%= t.artist %></a>
            </td>
            <td>
              <%= t.songs %>
            </td>
            <td class="edit">
              <% if t.user.id==current_user.id %>
              <%= link_to "編集", { :controller => "dbasses", :action => "edit",:id => t.id}, :method => :get ,:class => "edit_btn" %>
              <% end %>
            </td>
            <td class="edit">
              <% if t.user.id==current_user.id %>
              <%= link_to "削除", { :controller => "dbasses", :action => "destroy",:id => t.id}, :method => :delete ,:class => "edit_btn" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </table>

    </div>

    <%= link_to "メインページ", { :controller => "score", :action => "main"}, :method => :get ,:class => "back_btn" %>
  </body>
</html>

app/views/dbasses/new.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheets" href="/css/bootstrap.scss" />
    <link rel="stylesheets" href="/assets//dictations.scss" />
    <title>dictation</title>
  </head>
  <body class="dictation">
    <h1>スコア登録</h1>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dictation
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="../tweets/new">Band Score</a>
        <a class="dropdown-item" href="../partscores/new">Part Score</a>
        <a class="dropdown-item" href="/dictations/new">Dictation</a>
      </div>
    </div>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Bass
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="../dictations/new">Guitar</a>
        <a class="dropdown-item" href="/dbasses/new">Bass</a>
        <a class="dropdown-item" href="../ddrums/new">Drums</a>
        <a class="dropdown-item" href="../dkeyboards/new">Keyboard</a>
        <a class="dropdown-item" href="../d_choruses/new">Chorus</a>
      </div>
    </div>
    <%= form_for(@dbass, url:{controller:'dbasses', action:'create'})do |f| %>
    <div class="field">
      <p>歌手名</p>
      <small>(正式名で書く)</small>
      <br>
      <%= f.text_field :artist ,:class => "artist" %>
    </div>
    <div class="field">
      <p>曲名</p>
      <small>(正式名で書く)</small>
      <br>
      <%= f.text_field :songs ,:class => "songs" %>
    </div>
    <div class="field">
      <p>貸出者からの説明</p>
      <%= f.text_field :discription ,:class => "discription" %>
    </div>
    <div class="field">
      <p>貸出者からのお願い</p>
       <%= f.text_field :request ,:class => "request" %>
    </div>
    <div class="action">
       <input type="submit" name="commit" value="投稿する" data-disable-with="Create Dbass">
    </div>
    <% end %>
    <%= link_to "My Page", { :controller => "acount", :action => "mypage"}, :method => :get ,:class => "back_btn" %>
  </body>
</html>

app/views/dbasses/show.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheets" href="pbasses.scss" />
    <title>dictations</title>
  </head>
  <body class="pblist">
    <h1 class="Partscore">Dictations</h1>
    <div class="ptitle">
      <p>
        artist:
      </p>
      <h3 class="artist"><%= @dbass.artist %></h3>
      <h4 class="song"><%= @dbass.songs %></h4>
    </div>
    <div class="pchart">
      <div class="detail">
        <p>
          詳細
        </p>
      </div>
        <table class="pchart">

          <tr>
            <th class="first">
              貸出者
            </th>
            <td>
              <%= @dbass.user.username %>
            </td>
          </tr>
          <tr>
            <th>
              貸出者からの説明
            </th>
            <td>
              <%= @dbass.discription %>
            </td>
          </tr>
          <tr>
            <th>
              貸出者からのお願い
            </th>
            <td>
              <%= @dbass.request %>
            </td>
          </tr>

        </table>

    </div>
    <%= form_for(@dbass, url:{controller:'dbasses', action:'consent'})do |f| %>
    <%= f.hidden_field :id, value: @dbass.id %>
    <% end %>

    <% if @dbass.dbrequests.last == nil || @dbass.dbrequests.last.rent %>
      <%= link_to "借りる", dbass_consent_path(@dbass) ,:class => "back_btn" %>
    <% else %>
      <p class="back_btn">貸出中</p>
      <% if @dbass.user.id == current_user.id %>
        <%= link_to "返却", dbrequests_update_path(id: @dbass.id), :method => :put ,:class => "back_btn" %>
      <% end %>
    <% end %>
  </body>
</html>